-- =====================================================================
-- SAZO database schema v0.1  (PostgreSQL 16+)
-- Derived from: SAZO Domain Model v0.2, Rule Set v1, Decisions Log.
-- One schema per module (D-081). No foreign keys across schemas (DM-9):
-- cross-module references are plain UUIDs, checked by the owning module.
-- IDs are UUIDv7 generated by the application (DM-8); gen_random_uuid()
-- is only a fallback default for manual/admin inserts.
-- Enumerations are TEXT + CHECK (easier to extend than PG enums) (DM-10).
-- =====================================================================

-- (transaction is managed by the migration runner)

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid, digest
CREATE EXTENSION IF NOT EXISTS pg_trgm;    -- fuzzy plate/VIN search

-- ---------------------------------------------------------------------
-- platform: shared helpers only (no business data)
-- ---------------------------------------------------------------------
CREATE SCHEMA platform;

-- Append-only guard (D-020): attach to tables whose rows must never change.
CREATE FUNCTION platform.forbid_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'SAZO: % on %.% is not allowed (append-only table)',
    TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END $$;

CREATE FUNCTION platform.touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END $$;

-- Creates <schema>.outbox — one per module (D-081 rule 2).
CREATE FUNCTION platform.create_outbox(p_schema text) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  EXECUTE format($f$
    CREATE TABLE %I.outbox (
      id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      event_type    text NOT NULL,
      aggregate_id  uuid NOT NULL,
      payload       jsonb NOT NULL,
      occurred_at   timestamptz NOT NULL DEFAULT now(),
      published_at  timestamptz,
      attempts      int NOT NULL DEFAULT 0,
      last_error    text
    );
    CREATE INDEX ON %I.outbox (occurred_at) WHERE published_at IS NULL;
  $f$, p_schema, p_schema);
END $$;

CREATE FUNCTION platform.append_only(p_table regclass) RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  EXECUTE format('CREATE TRIGGER trg_append_only BEFORE UPDATE OR DELETE ON %s
                  FOR EACH ROW EXECUTE FUNCTION platform.forbid_mutation()', p_table);
END $$;

-- =====================================================================
-- 1. IDENTITY & ACCESS  (iam)
-- =====================================================================
CREATE SCHEMA iam;

CREATE TABLE iam.users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  display_name  text NOT NULL,
  phone_e164    text UNIQUE CHECK (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  email         text,
  status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','deleted')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CHECK (phone_e164 IS NOT NULL OR email IS NOT NULL)
);
CREATE UNIQUE INDEX users_email_uq ON iam.users (lower(email)) WHERE email IS NOT NULL;
CREATE TRIGGER trg_touch BEFORE UPDATE ON iam.users FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE iam.auth_identities (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid NOT NULL REFERENCES iam.users(id),
  provider     text NOT NULL CHECK (provider IN ('password','phone_otp','google','apple')),
  subject      text NOT NULL,
  secret_hash  text,
  verified_at  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, subject),
  CHECK (provider <> 'password' OR secret_hash IS NOT NULL)
);

CREATE TABLE iam.organisations (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type                   text NOT NULL CHECK (type IN ('garage','dealer','inspector','inspection_centre','police',
                           'revenue_authority','registry','lender','insurer','auction','rental','manufacturer','importer','sazo')),
  legal_name             text NOT NULL,
  trading_name           text,
  registration_number    text,
  district               text,
  address                text,
  contact_phone          text,
  contact_email          text,
  status                 text NOT NULL DEFAULT 'pending_verification'
                           CHECK (status IN ('pending_verification','approved','rejected','suspended')),
  approved_at            timestamptz,
  suspended_at           timestamptz,
  public_profile_enabled boolean NOT NULL DEFAULT false,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CHECK (status <> 'approved' OR approved_at IS NOT NULL)
);
CREATE TRIGGER trg_touch BEFORE UPDATE ON iam.organisations FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE iam.verification_cases (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id       uuid NOT NULL REFERENCES iam.organisations(id),
  status                text NOT NULL DEFAULT 'open' CHECK (status IN ('open','info_requested','approved','rejected')),
  submitted_evidence_ids uuid[] NOT NULL DEFAULT '{}',   -- obs.evidence_files (cross-module ref)
  reviewer_user_id      uuid REFERENCES iam.users(id),
  decision_reason       text,
  decided_at            timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE iam.permissions (
  code         text PRIMARY KEY,          -- e.g. 'vehicle.report.full.read', 'garage.job.create'
  description  text NOT NULL
);

CREATE TABLE iam.roles (
  id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code   text NOT NULL UNIQUE,            -- consumer, sazo_admin, org_manager, org_staff, partner_operator ...
  scope  text NOT NULL CHECK (scope IN ('platform','organisation')),
  name   text NOT NULL
);

CREATE TABLE iam.role_permissions (
  role_id          uuid NOT NULL REFERENCES iam.roles(id),
  permission_code  text NOT NULL REFERENCES iam.permissions(code),
  PRIMARY KEY (role_id, permission_code)
);

CREATE TABLE iam.platform_role_assignments (
  user_id     uuid NOT NULL REFERENCES iam.users(id),
  role_id     uuid NOT NULL REFERENCES iam.roles(id),
  granted_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE iam.memberships (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL REFERENCES iam.users(id),
  organisation_id  uuid NOT NULL REFERENCES iam.organisations(id),
  role_id          uuid NOT NULL REFERENCES iam.roles(id),
  status           text NOT NULL DEFAULT 'invited' CHECK (status IN ('invited','active','removed')),
  invited_by       uuid REFERENCES iam.users(id),
  joined_at        timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, organisation_id)
);
CREATE INDEX ON iam.memberships (organisation_id) WHERE status = 'active';

CREATE TABLE iam.audit_entries (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_user_id               uuid,
  acting_for_organisation_id  uuid,
  action                      text NOT NULL,
  target_type                 text NOT NULL,
  target_id                   uuid,
  details                     jsonb NOT NULL DEFAULT '{}',
  ip                          inet,
  at                          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON iam.audit_entries (target_type, target_id, at);
SELECT platform.append_only('iam.audit_entries');
SELECT platform.create_outbox('iam');

-- =====================================================================
-- 2. VEHICLE REGISTRY  (vehicle)
-- =====================================================================
CREATE SCHEMA vehicle;

CREATE TABLE vehicle.vehicles (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_ref                text NOT NULL UNIQUE CHECK (public_ref ~ '^SZV-[0-9A-HJKMNP-TV-Z]{4}-[0-9A-HJKMNP-TV-Z]{4}$'),
  status                    text NOT NULL CHECK (status IN ('active','provisional','merged','retired')),
  merged_into_id            uuid REFERENCES vehicle.vehicles(id),
  created_by_submission_id  uuid,              -- ingest.submissions
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'merged') = (merged_into_id IS NOT NULL)),
  CHECK (merged_into_id IS DISTINCT FROM id)
);
CREATE TRIGGER trg_touch BEFORE UPDATE ON vehicle.vehicles FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE vehicle.vehicle_identifiers (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id             uuid NOT NULL REFERENCES vehicle.vehicles(id),
  type                   text NOT NULL CHECK (type IN ('vin','chassis_number','registration_plate','engine_number','import_reference')),
  value_raw              text NOT NULL,
  value_normalized       text NOT NULL CHECK (value_normalized = upper(value_normalized) AND value_normalized !~ '[\s-]'),
  valid_from             timestamptz,
  valid_to               timestamptz,
  time_precision         text NOT NULL DEFAULT 'unknown' CHECK (time_precision IN ('exact','day','month','year','unknown')),
  status                 text NOT NULL DEFAULT 'active' CHECK (status IN ('active','historical','disputed')),
  change_reason          text CHECK (change_reason IN ('replacement','re_registration','personalised','correction')),  -- G6
  source_observation_id  uuid,                 -- obs.observations (provenance)
  created_at             timestamptz NOT NULL DEFAULT now(),
  CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
  CHECK (type <> 'vin' OR length(value_normalized) = 17 AND value_normalized !~ '[IOQ]')
);
-- Identity rule 1: an anchor (VIN/chassis) belongs to at most one vehicle while active.
CREATE UNIQUE INDEX vehicle_anchor_uq ON vehicle.vehicle_identifiers (type, value_normalized)
  WHERE type IN ('vin','chassis_number') AND status = 'active';
CREATE INDEX vehicle_ident_lookup ON vehicle.vehicle_identifiers (type, value_normalized);
CREATE INDEX vehicle_ident_trgm ON vehicle.vehicle_identifiers USING gin (value_normalized gin_trgm_ops);  -- G9 fuzzy
CREATE INDEX ON vehicle.vehicle_identifiers (vehicle_id);

CREATE TABLE vehicle.resolution_decisions (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_item_id     uuid NOT NULL,        -- ingest.submission_items
  presented_identifiers  jsonb NOT NULL,
  outcome                text NOT NULL CHECK (outcome IN ('matched','created_new','created_provisional','ambiguous','rejected')),
  matched_vehicle_id     uuid REFERENCES vehicle.vehicles(id),
  candidate_vehicle_ids  uuid[] NOT NULL DEFAULT '{}',
  rule_applied           text NOT NULL,
  score                  numeric(4,3),
  decided_by_user_id     uuid,                 -- NULL = system
  decided_at             timestamptz NOT NULL DEFAULT now(),
  CHECK (outcome NOT IN ('matched','created_new','created_provisional') OR matched_vehicle_id IS NOT NULL)
);
CREATE INDEX ON vehicle.resolution_decisions (submission_item_id);
CREATE INDEX ON vehicle.resolution_decisions (decided_at) WHERE outcome = 'ambiguous';
SELECT platform.append_only('vehicle.resolution_decisions');

CREATE TABLE vehicle.vehicle_merges (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  from_vehicle_id     uuid NOT NULL REFERENCES vehicle.vehicles(id),
  into_vehicle_id     uuid NOT NULL REFERENCES vehicle.vehicles(id),
  reason              text NOT NULL,
  reverses_merge_id   uuid REFERENCES vehicle.vehicle_merges(id),   -- DM-7: reversal is a new row
  decided_by_user_id  uuid NOT NULL,
  at                  timestamptz NOT NULL DEFAULT now(),
  CHECK (from_vehicle_id <> into_vehicle_id)
);
SELECT platform.append_only('vehicle.vehicle_merges');

CREATE TABLE vehicle.vehicle_splits (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_vehicle_id      uuid NOT NULL REFERENCES vehicle.vehicles(id),
  new_vehicle_id         uuid NOT NULL REFERENCES vehicle.vehicles(id),
  moved_observation_ids  uuid[] NOT NULL,
  reason                 text NOT NULL,
  decided_by_user_id     uuid NOT NULL,
  at                     timestamptz NOT NULL DEFAULT now()
);
SELECT platform.append_only('vehicle.vehicle_splits');
SELECT platform.create_outbox('vehicle');

-- =====================================================================
-- 3. INGESTION  (ingest)
-- =====================================================================
CREATE SCHEMA ingest;

CREATE TABLE ingest.sources (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code                     text NOT NULL UNIQUE,          -- e.g. 'REG-SIM', 'GAR-MUT'
  name                     text NOT NULL,
  organisation_id          uuid NOT NULL,                 -- iam.organisations
  domain                   text NOT NULL CHECK (domain IN ('registration','customs','police','finance','insurance','garage',
                             'inspection','auction','rental','manufacturer','dealer','owner','community','reference')),
  channel                  text NOT NULL CHECK (channel IN ('simulated_feed','partner_portal','garage_app','inspector_app',
                             'api','file_upload','ocr_assisted','user_submission')),
  is_simulated             boolean NOT NULL,              -- D-011
  default_evidence_class   text NOT NULL CHECK (default_evidence_class IN ('official','garage','inspection','dealer','owner_provided','community')),
  baseline_reputation      numeric(3,2) NOT NULL CHECK (baseline_reputation BETWEEN 0 AND 1),
  status                   text NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','retired')),
  superseded_by_source_id  uuid REFERENCES ingest.sources(id),
  active_from              timestamptz NOT NULL DEFAULT now(),
  active_to                timestamptz,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CHECK (status <> 'retired' OR active_to IS NOT NULL)
);
CREATE TRIGGER trg_touch BEFORE UPDATE ON ingest.sources FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE ingest.source_coverages (                     -- G2
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id    uuid NOT NULL REFERENCES ingest.sources(id),
  domain       text NOT NULL,
  scope        text NOT NULL CHECK (scope IN ('all_registered_vehicles','imports_since','own_customers','own_fleet','own_stock')),
  period_from  date NOT NULL,
  period_to    date,
  notes        text
);

CREATE TABLE ingest.mapping_versions (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id     uuid NOT NULL REFERENCES ingest.sources(id),
  version       int NOT NULL,
  mapping_spec  jsonb NOT NULL,
  active_from   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_id, version)
);
SELECT platform.append_only('ingest.mapping_versions');

CREATE TABLE ingest.submissions (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id                   uuid NOT NULL REFERENCES ingest.sources(id),
  submitted_by_user_id        uuid,
  acting_for_organisation_id  uuid,
  idempotency_key             text NOT NULL,
  received_at                 timestamptz NOT NULL DEFAULT now(),
  raw_payload                 jsonb,
  raw_file_id                 uuid,                          -- obs.evidence_files
  payload_sha256              text NOT NULL CHECK (payload_sha256 ~ '^[0-9a-f]{64}$'),
  schema_version              int NOT NULL,
  status                      text NOT NULL DEFAULT 'received'
                                CHECK (status IN ('received','validating','accepted','partially_accepted','rejected','processed')),
  status_reason               text,
  UNIQUE (source_id, idempotency_key),                         -- X5: resend stored once
  CHECK (raw_payload IS NOT NULL OR raw_file_id IS NOT NULL)
);
CREATE INDEX ON ingest.submissions (status, received_at) WHERE status IN ('received','validating');

CREATE TABLE ingest.submission_items (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id           uuid NOT NULL REFERENCES ingest.submissions(id),
  sequence                int NOT NULL,
  raw_item                jsonb NOT NULL,
  status                  text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','needs_review')),
  errors                  jsonb NOT NULL DEFAULT '[]',
  warnings                jsonb NOT NULL DEFAULT '[]',
  resolution_decision_id  uuid,                                 -- vehicle.resolution_decisions
  UNIQUE (submission_id, sequence)
);

CREATE TABLE ingest.ocr_extractions (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  evidence_file_id      uuid NOT NULL,                          -- obs.evidence_files
  engine                text NOT NULL,
  engine_version        text NOT NULL,
  raw_output            jsonb NOT NULL,
  proposed_fields       jsonb NOT NULL,
  confirmed_fields      jsonb,
  confirmed_by_user_id  uuid,
  confirmed_at          timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  CHECK ((confirmed_fields IS NULL) = (confirmed_at IS NULL))
);
SELECT platform.create_outbox('ingest');

-- =====================================================================
-- 4. OBSERVATIONS & EVIDENCE  (obs)  +  restricted personal data (pii)
-- =====================================================================
CREATE SCHEMA obs;

CREATE TABLE obs.observation_types (                          -- the catalogue, as data (DM-3)
  code                 text NOT NULL,
  schema_version       int NOT NULL,
  domain               text NOT NULL,
  json_schema          jsonb NOT NULL,
  default_sensitivity  text NOT NULL CHECK (default_sensitivity IN ('public','restricted','confidential')),
  required_evidence    text[] NOT NULL DEFAULT '{}',          -- D-057, e.g. {odometer_photo}
  active               boolean NOT NULL DEFAULT true,
  PRIMARY KEY (code, schema_version)
);

CREATE TABLE obs.vehicle_events (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id            uuid NOT NULL,                          -- vehicle.vehicles
  type                  text NOT NULL CHECK (type IN ('garage_job','inspection','import','registration','transfer','accident',
                          'auction_sale','finance_change','police_report','rental_period','insurance_event','owner_submission','other')),
  event_time            timestamptz,
  event_time_precision  text NOT NULL CHECK (event_time_precision IN ('exact','day','month','year','unknown')),
  source_id             uuid NOT NULL,                          -- ingest.sources
  submission_id         uuid NOT NULL,                          -- ingest.submissions
  summary_key           text,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON obs.vehicle_events (vehicle_id, event_time);
SELECT platform.append_only('obs.vehicle_events');

CREATE TABLE obs.observations (
  id                          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id                  uuid NOT NULL,                    -- as resolved at ingestion; merges followed at read time (DM-7)
  event_id                    uuid REFERENCES obs.vehicle_events(id),
  type                        text NOT NULL,
  type_schema_version         int NOT NULL,
  attributes                  jsonb NOT NULL,
  event_time                  timestamptz,
  event_time_precision        text NOT NULL CHECK (event_time_precision IN ('exact','day','month','year','unknown')),
  recorded_at                 timestamptz NOT NULL DEFAULT now(),   -- D-021
  source_id                   uuid NOT NULL,
  submission_item_id          uuid NOT NULL,
  entered_by_user_id          uuid,
  acting_for_organisation_id  uuid,
  evidence_class              text NOT NULL CHECK (evidence_class IN ('official','garage','inspection','dealer','owner_provided','community')),
  sensitivity                 text NOT NULL CHECK (sensitivity IN ('public','restricted','confidential')),
  mapping_version             int,
  FOREIGN KEY (type, type_schema_version) REFERENCES obs.observation_types(code, schema_version),
  CHECK (event_time IS NOT NULL OR event_time_precision = 'unknown')
);
CREATE INDEX obs_by_vehicle ON obs.observations (vehicle_id, type, event_time);
CREATE INDEX obs_by_event ON obs.observations (event_id);
CREATE INDEX obs_by_source ON obs.observations (source_id, recorded_at);
CREATE INDEX obs_attr ON obs.observations USING gin (attributes jsonb_path_ops);
SELECT platform.append_only('obs.observations');

CREATE TABLE obs.observation_relations (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  from_observation_id  uuid NOT NULL REFERENCES obs.observations(id),
  to_observation_id    uuid NOT NULL REFERENCES obs.observations(id),
  kind                 text NOT NULL CHECK (kind IN ('corrects','retracts','duplicates','corroborates')),
  reason               text,
  created_by_user_id   uuid,
  created_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (from_observation_id, to_observation_id, kind),
  CHECK (from_observation_id <> to_observation_id)
);
CREATE INDEX ON obs.observation_relations (to_observation_id);
SELECT platform.append_only('obs.observation_relations');

CREATE TABLE obs.observation_attributions (                  -- re-attribution after a vehicle split
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  observation_id      uuid NOT NULL REFERENCES obs.observations(id),
  vehicle_id          uuid NOT NULL,
  split_id            uuid NOT NULL,                          -- vehicle.vehicle_splits
  at                  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON obs.observation_attributions (observation_id, at DESC);
SELECT platform.append_only('obs.observation_attributions');

CREATE TABLE obs.evidence_files (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  storage_key          text NOT NULL UNIQUE,                  -- S3 key; object stored write-once
  sha256               text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  mime_type            text NOT NULL,
  size_bytes           bigint NOT NULL CHECK (size_bytes > 0),
  kind                 text NOT NULL CHECK (kind IN ('odometer_photo','engine_number_photo','plate_photo','vehicle_photo','receipt',
                         'invoice','part_photo','inspection_report','official_document','org_verification_document','other')),
  captured_at          timestamptz,
  uploaded_at          timestamptz NOT NULL DEFAULT now(),
  uploaded_by_user_id  uuid,
  capture_metadata     jsonb NOT NULL DEFAULT '{}',
  retention_class      text NOT NULL DEFAULT 'standard' CHECK (retention_class IN ('standard','legal_hold','personal'))
);
CREATE INDEX ON obs.evidence_files (sha256);
SELECT platform.append_only('obs.evidence_files');

CREATE TABLE obs.observation_evidence (
  observation_id    uuid NOT NULL REFERENCES obs.observations(id),
  evidence_file_id  uuid NOT NULL REFERENCES obs.evidence_files(id),
  role              text NOT NULL CHECK (role IN ('primary','supporting')),
  PRIMARY KEY (observation_id, evidence_file_id)
);
CREATE INDEX ON obs.observation_evidence (evidence_file_id);
SELECT platform.append_only('obs.observation_evidence');

CREATE TABLE obs.attestation_requests (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_event_id  uuid NOT NULL REFERENCES obs.vehicle_events(id),
  party_id         uuid NOT NULL,                           -- pii.parties
  channel          text NOT NULL CHECK (channel IN ('sms_reply','sms_link','app')),
  message_id       uuid,                                    -- notify.outbound_messages
  requested_at     timestamptz NOT NULL DEFAULT now(),
  expires_at       timestamptz NOT NULL
);
SELECT platform.append_only('obs.attestation_requests');

CREATE TABLE obs.attestations (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id             uuid REFERENCES obs.attestation_requests(id),
  target_event_id        uuid REFERENCES obs.vehicle_events(id),
  target_observation_id  uuid REFERENCES obs.observations(id),
  attester_kind          text NOT NULL CHECK (attester_kind IN ('registered_owner','customer','inspector','organisation')),  -- G3
  attester_party_id      uuid,
  channel                text NOT NULL CHECK (channel IN ('sms_reply','sms_link','app')),
  response               text NOT NULL CHECK (response IN ('confirmed','disputed','no_response')),
  comment                text,
  responded_at           timestamptz NOT NULL DEFAULT now(),
  CHECK ((target_event_id IS NULL) <> (target_observation_id IS NULL))
);
CREATE INDEX ON obs.attestations (target_event_id);
SELECT platform.append_only('obs.attestations');
SELECT platform.create_outbox('obs');

-- Restricted personal data (DM-2). Separate schema so it can get its own DB role,
-- encryption, backup and erasure policy. Ciphertext is produced by the app (KMS envelope).
CREATE SCHEMA pii;

CREATE TABLE pii.parties (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind                  text NOT NULL CHECK (kind IN ('person','business')),
  name_ciphertext       bytea,
  phone_ciphertext      bytea,
  phone_hash            bytea,          -- HMAC-SHA256(phone, secret) for matching without decrypting
  national_id_hash      bytea,
  key_version           int NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  erasure_requested_at  timestamptz,
  erased_at             timestamptz,
  CHECK (erased_at IS NULL OR (name_ciphertext IS NULL AND phone_ciphertext IS NULL))
);
CREATE INDEX ON pii.parties (phone_hash) WHERE phone_hash IS NOT NULL;

CREATE TABLE pii.party_consents (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  party_id    uuid NOT NULL REFERENCES pii.parties(id),
  purpose     text NOT NULL CHECK (purpose IN ('attestation_sms','service_reminders','marketing')),
  channel     text NOT NULL,
  granted_at  timestamptz NOT NULL DEFAULT now(),
  revoked_at  timestamptz
);

-- =====================================================================
-- 5. TRUST  (trust) — all derived, recomputable, versioned (D-022)
-- =====================================================================
CREATE SCHEMA trust;

CREATE TABLE trust.rule_sets (
  version       text PRIMARY KEY,           -- 'rs-2026.10-v1'
  description   text NOT NULL,
  parameters    jsonb NOT NULL,             -- Rule Set §11 tunables
  activated_at  timestamptz,
  activated_by  uuid
);

CREATE TABLE trust.derivation_runs (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id        uuid NOT NULL,
  rule_set_version  text NOT NULL REFERENCES trust.rule_sets(version),
  as_of             timestamptz NOT NULL,                       -- G4
  trigger           text NOT NULL CHECK (trigger IN ('observation','attestation','merge','split','rule_change','manual','full_rebuild')),
  status            text NOT NULL DEFAULT 'running' CHECK (status IN ('running','succeeded','failed')),
  started_at        timestamptz NOT NULL DEFAULT now(),
  finished_at       timestamptz,
  error             text
);
CREATE INDEX ON trust.derivation_runs (vehicle_id, finished_at DESC) WHERE status = 'succeeded';

-- Pointer to each vehicle's latest successful run: what every read uses.
CREATE TABLE trust.vehicle_current_run (
  vehicle_id  uuid PRIMARY KEY,
  run_id      uuid NOT NULL REFERENCES trust.derivation_runs(id),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trust.source_reputations (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id         uuid NOT NULL,
  score             numeric(4,3) NOT NULL CHECK (score BETWEEN 0 AND 1),
  factors           jsonb NOT NULL,           -- {confirmed, disputed, baseline, suspended...}
  rule_set_version  text NOT NULL REFERENCES trust.rule_sets(version),
  as_of             timestamptz NOT NULL,
  computed_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON trust.source_reputations (source_id, as_of DESC);
SELECT platform.append_only('trust.source_reputations');

CREATE TABLE trust.observation_assessments (
  run_id            uuid NOT NULL REFERENCES trust.derivation_runs(id),
  observation_id    uuid NOT NULL,
  vehicle_id        uuid NOT NULL,
  confidence        numeric(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  weak              boolean NOT NULL,
  excluded          boolean NOT NULL,
  exclusion_reason  text CHECK (exclusion_reason IN ('retracted','corrected','retired_simulated_source','duplicate')),
  factors           jsonb NOT NULL,           -- explanation (D-024)
  PRIMARY KEY (run_id, observation_id),
  CHECK (excluded = (exclusion_reason IS NOT NULL))
);

CREATE TABLE trust.consistency_flags (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id           uuid NOT NULL REFERENCES trust.derivation_runs(id),
  vehicle_id       uuid NOT NULL,
  check_code       text NOT NULL CHECK (check_code IN ('mileage_decrease','implausible_mileage_rate','undeclared_engine_change',
                     'plate_vin_mismatch','cloned_plate_suspected','identity_collision','duplicate_suspected','date_impossible','spec_mismatch')),
  severity         text NOT NULL CHECK (severity IN ('info','attention','serious')),
  observation_ids  uuid[] NOT NULL,
  details          jsonb NOT NULL DEFAULT '{}'
);
CREATE INDEX ON trust.consistency_flags (run_id);

-- Conflicts outlive runs: they have a human lifecycle.
CREATE TABLE trust.conflicts (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id           uuid NOT NULL,
  topic                text NOT NULL CHECK (topic IN ('mileage','identity','ownership','damage','finance','spec','care','legal')),
  status               text NOT NULL DEFAULT 'open' CHECK (status IN ('open','under_review','auto_resolved','resolved','dismissed')),
  observation_ids      uuid[] NOT NULL,
  opened_by_check      text,
  related_vehicle_ids  uuid[] NOT NULL DEFAULT '{}',   -- e.g. both vehicles in a cloned-plate case
  assigned_to_user_id  uuid,
  resolution           jsonb,                           -- {interpretation, reasoning}
  resolved_by_user_id  uuid,
  resolved_by_rule     text,
  opened_at            timestamptz NOT NULL DEFAULT now(),
  resolved_at          timestamptz,
  CHECK (status NOT IN ('resolved','dismissed') OR (resolution IS NOT NULL AND resolved_by_user_id IS NOT NULL)),
  CHECK (status <> 'auto_resolved' OR resolved_by_rule IS NOT NULL)
);
CREATE INDEX ON trust.conflicts (vehicle_id) WHERE status IN ('open','under_review');
CREATE INDEX ON trust.conflicts (status, opened_at) WHERE status IN ('open','under_review');

CREATE TABLE trust.conflict_activities (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conflict_id  uuid NOT NULL REFERENCES trust.conflicts(id),
  kind         text NOT NULL CHECK (kind IN ('opened','observation_added','assigned','commented','status_changed','resolved','reopened')),
  actor_user_id uuid,
  details      jsonb NOT NULL DEFAULT '{}',
  at           timestamptz NOT NULL DEFAULT now()
);
SELECT platform.append_only('trust.conflict_activities');

CREATE TABLE trust.canonical_facts (
  run_id                      uuid NOT NULL REFERENCES trust.derivation_runs(id),
  vehicle_id                  uuid NOT NULL,
  key                         text NOT NULL,     -- make, model, current_mileage_km, title_status, ...
  value                       jsonb NOT NULL,
  confidence                  numeric(4,3) NOT NULL,
  estimated                   boolean NOT NULL DEFAULT false,
  supporting_observation_ids  uuid[] NOT NULL DEFAULT '{}',
  conflicting_observation_ids uuid[] NOT NULL DEFAULT '{}',
  PRIMARY KEY (run_id, key)
);

CREATE TABLE trust.question_assessments (
  run_id                 uuid NOT NULL REFERENCES trust.derivation_runs(id),
  vehicle_id             uuid NOT NULL,
  question               text NOT NULL CHECK (question IN ('identity','care','damage','mileage','provenance','legal_financial','valuation')),
  status                 text NOT NULL CHECK (status IN ('verified','attention','serious','not_available')),
  headline_key           text NOT NULL,
  params                 jsonb NOT NULL DEFAULT '{}',
  notes                  jsonb NOT NULL DEFAULT '[]',
  coverage               jsonb NOT NULL DEFAULT '{}',
  basis_observation_ids  uuid[] NOT NULL DEFAULT '{}',
  PRIMARY KEY (run_id, question)
);

CREATE TABLE trust.record_confidences (
  run_id      uuid PRIMARY KEY REFERENCES trust.derivation_runs(id),
  vehicle_id  uuid NOT NULL,
  level       text NOT NULL CHECK (level IN ('high','medium','low','insufficient')),
  factors     jsonb NOT NULL      -- {records, sources, open_conflicts}
);
SELECT platform.create_outbox('trust');

-- =====================================================================
-- 6. REPORTS  (report) — read models + sharing
-- =====================================================================
CREATE SCHEMA report;

CREATE TABLE report.exposure_policies (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_version    int NOT NULL,
  observation_type  text NOT NULL,
  attribute         text NOT NULL,        -- '*' = whole observation
  audience          text NOT NULL CHECK (audience IN ('public','consumer','owner','garage','dealer','partner','sazo_reviewer')),
  visibility        text NOT NULL CHECK (visibility IN ('full','summarised','hidden')),
  UNIQUE (policy_version, observation_type, attribute, audience)
);

CREATE TABLE report.public_summary_cache (
  vehicle_id    uuid PRIMARY KEY,
  trust_run_id  uuid NOT NULL,
  content       jsonb NOT NULL,           -- already filtered for 'public'
  built_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE report.full_report_cache (
  vehicle_id    uuid NOT NULL,
  audience      text NOT NULL,
  trust_run_id  uuid NOT NULL,
  content       jsonb NOT NULL,
  built_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (vehicle_id, audience)
);

CREATE TABLE report.report_snapshots (    -- frozen copy for PDF/share
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_ref          text NOT NULL UNIQUE,   -- SZR-...
  vehicle_id          uuid NOT NULL,
  audience            text NOT NULL,
  trust_run_id        uuid NOT NULL,
  content             jsonb NOT NULL,
  created_by_user_id  uuid,
  created_at          timestamptz NOT NULL DEFAULT now()
);
SELECT platform.append_only('report.report_snapshots');

CREATE TABLE report.shared_links (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token_hash          text NOT NULL UNIQUE,
  snapshot_id         uuid NOT NULL REFERENCES report.report_snapshots(id),
  created_by_user_id  uuid,
  expires_at          timestamptz,
  revoked_at          timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE report.saved_checks (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL,
  vehicle_id  uuid NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, vehicle_id)
);

CREATE TABLE report.search_events (       -- anti-scraping and analytics; no raw query stored
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid,
  client_key     text NOT NULL,           -- hashed IP/device for anonymous rate limits
  query_hash     text NOT NULL,
  query_kind     text NOT NULL CHECK (query_kind IN ('vin','chassis','plate','unknown')),
  result_count   int NOT NULL,
  at             timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON report.search_events (client_key, at);
SELECT platform.create_outbox('report');

-- =====================================================================
-- 7. GARAGE  (garage)
-- =====================================================================
CREATE SCHEMA garage;

CREATE TABLE garage.profiles (
  organisation_id   uuid PRIMARY KEY,      -- iam.organisations (type = garage)
  services_offered  text[] NOT NULL DEFAULT '{}',
  opening_hours     jsonb,
  latitude          numeric(8,5),
  longitude         numeric(8,5),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE garage.jobs (
  id                  uuid PRIMARY KEY,                -- generated on the phone (offline), UUIDv7
  public_ref          text NOT NULL UNIQUE,            -- GJ-...
  organisation_id     uuid NOT NULL,
  created_by_user_id  uuid NOT NULL,
  plate_entered       text NOT NULL,
  vehicle_id          uuid,                            -- set once resolved
  work_types          text[] NOT NULL CHECK (cardinality(work_types) > 0),
  form                jsonb NOT NULL,                  -- the step-by-step answers
  status              text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','accepted','rejected')),
  client_created_at   timestamptz NOT NULL,            -- device time, offline-safe
  submitted_at        timestamptz,
  submission_id       uuid,                            -- ingest.submissions
  rejection_reason    text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CHECK (status = 'draft' OR submitted_at IS NOT NULL)
);
CREATE INDEX ON garage.jobs (organisation_id, created_at DESC);
CREATE TRIGGER trg_touch BEFORE UPDATE ON garage.jobs FOR EACH ROW EXECUTE FUNCTION platform.touch_updated_at();

CREATE TABLE garage.job_customers (
  job_id                uuid PRIMARY KEY REFERENCES garage.jobs(id),
  party_id              uuid,                          -- pii.parties
  phone_provided        boolean NOT NULL,
  sms_consent           boolean NOT NULL DEFAULT false
);

CREATE TABLE garage.job_evidence (
  job_id            uuid NOT NULL REFERENCES garage.jobs(id),
  evidence_file_id  uuid NOT NULL,                     -- obs.evidence_files
  kind              text NOT NULL,
  PRIMARY KEY (job_id, evidence_file_id)
);
SELECT platform.create_outbox('garage');

-- =====================================================================
-- 8. NOTIFICATIONS  (notify)
-- =====================================================================
CREATE SCHEMA notify;

CREATE TABLE notify.templates (
  code     text NOT NULL,
  version  int NOT NULL,
  channel  text NOT NULL CHECK (channel IN ('sms','email')),
  locale   text NOT NULL DEFAULT 'en-UG',
  body     text NOT NULL,
  PRIMARY KEY (code, version, locale)
);

CREATE TABLE notify.outbound_messages (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  channel              text NOT NULL CHECK (channel IN ('sms','email')),
  to_party_id          uuid,                 -- pii.parties
  to_user_id           uuid,                 -- iam.users
  template_code        text NOT NULL,
  template_version     int NOT NULL,
  params               jsonb NOT NULL DEFAULT '{}',
  purpose              text NOT NULL CHECK (purpose IN ('attestation','otp','account','reminder')),
  related_type         text,
  related_id           uuid,
  status               text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','delivered','failed')),
  provider             text,
  provider_message_id  text,
  failed_reason        text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  sent_at              timestamptz,
  delivered_at         timestamptz,
  CHECK (to_party_id IS NOT NULL OR to_user_id IS NOT NULL)
);
CREATE INDEX ON notify.outbound_messages (status, created_at) WHERE status = 'queued';

CREATE TABLE notify.inbound_replies (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  channel             text NOT NULL CHECK (channel IN ('sms')),
  from_phone_hash     bytea NOT NULL,
  body                text NOT NULL,
  provider_message_id text,
  received_at         timestamptz NOT NULL DEFAULT now(),
  matched_message_id  uuid REFERENCES notify.outbound_messages(id),
  processed_at        timestamptz
);
SELECT platform.create_outbox('notify');

-- =====================================================================
-- 9. REFERENCE & INTELLIGENCE  (ref)
-- =====================================================================
CREATE SCHEMA ref;

CREATE TABLE ref.vehicle_models (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  make         text NOT NULL,
  model        text NOT NULL,
  generation   text NOT NULL,          -- e.g. 'XU60 (2013–2020)'
  body         text,
  year_from    int NOT NULL,
  year_to      int,
  model_codes  text[] NOT NULL DEFAULT '{}',   -- ZSU60, NZT260 ... used to infer model from chassis
  UNIQUE (make, model, generation)
);
CREATE INDEX ON ref.vehicle_models USING gin (model_codes);

CREATE TABLE ref.service_intervals (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id         uuid NOT NULL REFERENCES ref.vehicle_models(id),
  item             text NOT NULL,       -- engine_oil, brake_pads, tyres, battery, timing_belt, cvt_fluid ...
  interval_km      int,
  interval_months  int,
  data_version     int NOT NULL,
  CHECK (interval_km IS NOT NULL OR interval_months IS NOT NULL)
);

CREATE TABLE ref.price_list_items (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_family    text NOT NULL,
  item            text NOT NULL,
  parts_ugx_p25   bigint, parts_ugx_p50 bigint, parts_ugx_p75 bigint,
  labour_ugx_p25  bigint, labour_ugx_p50 bigint, labour_ugx_p75 bigint,
  basis           text NOT NULL CHECK (basis IN ('simulated','garage_jobs','survey')),
  observed_from   date NOT NULL,
  observed_to     date NOT NULL,
  data_version    int NOT NULL
);

CREATE TABLE ref.market_comparables (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id         uuid NOT NULL REFERENCES ref.vehicle_models(id),
  year             int NOT NULL,
  mileage_km       int,
  price_ugx        bigint NOT NULL CHECK (price_ugx > 0),
  sold_on          date NOT NULL,
  condition_flags  text[] NOT NULL DEFAULT '{}',   -- accident, structural, flood, rebuilt
  basis            text NOT NULL CHECK (basis IN ('simulated','dealer_listing','auction','sale_record')),
  data_version     int NOT NULL
);
CREATE INDEX ON ref.market_comparables (model_id, year, sold_on);

CREATE TABLE ref.model_guidance (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id      uuid NOT NULL REFERENCES ref.vehicle_models(id),
  kind          text NOT NULL CHECK (kind IN ('vin_locations','common_issues','parts_availability','buyer_checklist')),
  content       jsonb NOT NULL,
  data_version  int NOT NULL
);

CREATE TABLE ref.valuations (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id         uuid NOT NULL,
  trust_run_id       uuid NOT NULL,
  rule_set_version   text NOT NULL,
  as_of              timestamptz NOT NULL,
  comparables_count  int NOT NULL,
  range_low_ugx      bigint,
  range_high_ugx     bigint,
  point_ugx          bigint,
  status             text NOT NULL CHECK (status IN ('verified','attention','not_available')),
  adjustments        jsonb NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  CHECK (status = 'not_available' OR (range_low_ugx <= point_ugx AND point_ugx <= range_high_ugx))
);
CREATE INDEX ON ref.valuations (vehicle_id, created_at DESC);

CREATE TABLE ref.maintenance_forecasts (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id        uuid NOT NULL,
  trust_run_id      uuid NOT NULL,
  rule_set_version  text NOT NULL,
  as_of             timestamptz NOT NULL,
  items             jsonb NOT NULL,
  total_low_ugx     bigint,
  total_high_ugx    bigint,
  assumptions       jsonb NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON ref.maintenance_forecasts (vehicle_id, created_at DESC);

CREATE TABLE ref.vehicle_health (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id        uuid NOT NULL,
  trust_run_id      uuid NOT NULL,
  rule_set_version  text NOT NULL,
  as_of             timestamptz NOT NULL,
  insufficient      boolean NOT NULL,
  score             int CHECK (score BETWEEN 0 AND 100),
  band              text CHECK (band IN ('good','fair','poor')),
  deductions        jsonb NOT NULL DEFAULT '[]',
  created_at        timestamptz NOT NULL DEFAULT now(),
  CHECK (insufficient = (score IS NULL))             -- D-062: never a number without enough history
);
CREATE INDEX ON ref.vehicle_health (vehicle_id, created_at DESC);
SELECT platform.create_outbox('ref');

-- =====================================================================
-- 10. COMMUNITY  (community)
-- =====================================================================
CREATE SCHEMA community;

CREATE TABLE community.model_reviews (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id        uuid NOT NULL,          -- ref.vehicle_models (D-063: model, never a vehicle)
  author_user_id  uuid NOT NULL,
  verified_owner  boolean NOT NULL DEFAULT false,
  rating          smallint CHECK (rating BETWEEN 1 AND 5),
  body            text NOT NULL,
  status          text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','published','rejected','removed')),
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE community.creator_links (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id              uuid NOT NULL,
  url                   text NOT NULL CHECK (url ~ '^https://'),
  platform              text NOT NULL CHECK (platform IN ('tiktok','youtube','instagram','other')),
  title                 text,
  submitted_by_user_id  uuid NOT NULL,
  status                text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','published','rejected','removed')),  -- P-008
  created_at            timestamptz NOT NULL DEFAULT now(),
  UNIQUE (model_id, url)
);

CREATE TABLE community.moderation_cases (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_type       text NOT NULL CHECK (target_type IN ('model_review','creator_link')),
  target_id         uuid NOT NULL,
  status            text NOT NULL DEFAULT 'open' CHECK (status IN ('open','approved','rejected')),
  reviewer_user_id  uuid,
  reason            text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  decided_at        timestamptz
);
SELECT platform.create_outbox('community');
