// Generates src/components/icon-paths.ts from Material Symbols (Apache-2.0) — only the icons SAZO uses,
// as inline SVG paths, so pages stay light on mobile data (no 3 MB icon font).
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);
const dir = path.join(path.dirname(require.resolve('@material-symbols/svg-500/package.json')), 'outlined');
const DEFAULT_NAMES = [
  'search', 'verified', 'check_circle', 'info', 'error', 'report', 'help', 'hourglass_empty', 'directions_car', 'history',
  'receipt_long', 'photo_camera', 'speed', 'build', 'schedule', 'arrow_forward', 'arrow_back', 'logout', 'person', 'sms',
  'close', 'keyboard_arrow_down', 'chevron_forward', 'garage', 'description', 'local_police', 'account_balance', 'payments', 'timeline', 'travel_explore',
  'thumb_up', 'thumb_down', 'lock', 'science', 'warning', 'format_paint', 'car_crash', 'public', 'sell', 'list_alt',
  'add', 'delete', 'share', 'bookmark', 'bookmark_added', 'compare_arrows', 'key', 'upload_file', 'star', 'forum', 'play_circle', 'gavel',
];
// Usage: node build-icons.mjs [output.ts] [name,name,...]  (defaults: the web app's icon set)
const [, , outArg, namesArg] = process.argv;
const NAMES = namesArg ? namesArg.split(',') : DEFAULT_NAMES;
const out = {};
for (const name of NAMES) {
  const svg = readFileSync(path.join(dir, `${name}.svg`), 'utf8');
  const paths = [...svg.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]);
  const vb = svg.match(/viewBox="([^"]+)"/)[1];
  out[name] = { vb, d: paths.join(' ') };
}
writeFileSync(outArg ? path.resolve(outArg) : new URL('../src/components/icon-paths.ts', import.meta.url),
  `// Generated by scripts/build-icons.mjs from @material-symbols/svg-500 (Apache-2.0). Do not edit.\n` +
  `export const ICONS = ${JSON.stringify(out, null, 0)} as const;\nexport type IconName = keyof typeof ICONS;\n`);
console.log(`${NAMES.length} icons written`);
