// Rule Set v1 tunable parameters (docs/design/rule-set-v1.md §11). Changing any value = new rule-set version.
export const RULE_SET_VERSION = 'rs-2026.10-v1';

export const PARAMS = {
  weakThreshold: 0.4,
  lowGarageReputation: 0.6,
  baseline: { official: 0.9, inspection: 0.85, garage: 0.7, dealer: 0.6, owner_provided: 0.35, community: 0.2 },
  garageReputation: { confirmWeight: 0.15, disputeWeight: 0.8, smoothing: 5, min: 0.3, max: 0.9, suspendedCap: 0.3 },
  evidenceBonus: 0.1,
  corroboration: { each: 0.05, max: 0.1, withinDays: 180 },
  attestation: {
    registered_owner: { confirmed: 0.1, disputed: -0.3 },
    customer: { confirmed: 0.05, disputed: -0.15 },
    inspector: { confirmed: 0.1, disputed: -0.3 },
    organisation: { confirmed: 0.05, disputed: -0.15 },
  },
  flagPenalty: { serious: -0.3, attention: -0.15 },
  legacyPenalty: -0.1,
  confidenceClamp: { min: 0.05, max: 0.99 },
  mileage: {
    decreaseTolerance: 0.01,
    minDaysBetweenForRate: 30,
    annualThreshold: { private: 60_000, rental: 100_000, commercial: 150_000, psv: 150_000 },
    absoluteMax: 1_000_000,
    verifiedMinSpanMonths: 6,
  },
  care: { windowMonths: 36, gapMonths: 24, minAvgConfidence: 0.6 },
  legal: { recoveryWindowMonths: 36, impoundReleaseWindowMonths: 12 },
  dateImpossibleGraceDays: 31,
  recordConfidence: { insufficientBelow: 3, lowBelow: 5, highMinRecords: 8, highMinSources: 3 },
  health: {
    baseWithRecentInspection: 95,
    baseOtherwise: 85,
    recentInspectionMonths: 12,
    structural: -25,
    rebuilt: -35,
    flood: -30,
    accidentEach: -8,
    accidentMax: -16,
    mileageSerious: -20,
    mileageAttention: -5,
    odometerReplaced: -5,
    rentalOrPsv: -10,
    careAttention: -8,
    per50kOver50k: -5,
    mileageMax: -20,
    agePerYearOver8: -1,
    ageMax: -10,
    defectMinor: -2,
    defectMajor: -10,
  },
  valuation: { verifiedMin: 5, attentionMin: 2 },
} as const;
